# Generated by Django 4.2.10 on 2024-03-17 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avatar', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label_1', models.CharField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='Meadow',
        ),
    ]
