# Generated by Django 4.2.10 on 2024-03-17 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avatar', '0002_testmodel_delete_meadow'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestMode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label_1', models.CharField(max_length=100)),
                ('label_2', models.CharField(max_length=100)),
                ('label_3', models.CharField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='TestModel',
        ),
    ]
