# Generated by Django 5.0.3 on 2024-03-18 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avatar', '0003_testmode_delete_testmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label_0', models.CharField(max_length=100)),
                ('label_1', models.CharField(max_length=100)),
                ('label_2', models.CharField(max_length=100)),
                ('label_3', models.CharField(max_length=100)),
                ('label_4', models.CharField(max_length=100)),
                ('label_5', models.CharField(max_length=100)),
                ('label_6', models.CharField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='TestMode',
        ),
    ]
