# Generated by Django 4.2.11 on 2024-05-04 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avatar', '0009_testmodel_classidx_alter_testmodel_squataccuracy'),
    ]

    operations = [
        migrations.CreateModel(
            name='Keyanglestest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('left_knee_angle', models.FloatField(null=True)),
                ('right_knee_angle', models.FloatField(null=True)),
                ('left_hip_angle', models.FloatField(null=True)),
                ('right_hip_angle', models.FloatField(null=True)),
                ('left_inside_hip_angle', models.FloatField(null=True)),
                ('right_inside_hip_angle', models.FloatField(null=True)),
                ('ratio_foot_to_shoulder', models.FloatField(null=True)),
                ('ratio_foot_to_hip', models.FloatField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Keypointstest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('left_kneex', models.FloatField(null=True)),
                ('right_kneex', models.FloatField(null=True)),
                ('left_hipx', models.FloatField(null=True)),
                ('right_hipx', models.FloatField(null=True)),
                ('left_shoulderx', models.FloatField(null=True)),
                ('right_shoulderx', models.FloatField(null=True)),
                ('left_kneey', models.FloatField(null=True)),
                ('right_kneey', models.FloatField(null=True)),
                ('left_hipy', models.FloatField(null=True)),
                ('right_hipy', models.FloatField(null=True)),
                ('left_shouldery', models.FloatField(null=True)),
                ('right_shouldery', models.FloatField(null=True)),
                ('left_foot', models.FloatField(null=True)),
                ('right_foot', models.FloatField(null=True)),
                ('left_ankle', models.FloatField(null=True)),
                ('right_ankle', models.FloatField(null=True)),
                ('left_heel', models.FloatField(null=True)),
                ('right_heel', models.FloatField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SampleDatas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sampling_ratio1', models.FloatField()),
                ('sampling_ratio2', models.FloatField()),
                ('sampling_ratio3', models.FloatField()),
                ('sampling_knee_coef_down', models.FloatField()),
                ('sampling_knee_intercept_down', models.FloatField()),
                ('sampling_hip_coef_down', models.FloatField()),
                ('sampling_hip_intercept_down', models.FloatField()),
                ('sampling_inside_hip_coef_down', models.FloatField()),
                ('sampling_inside_hip_intercept_down', models.FloatField()),
                ('sampling_knee_coef_up', models.FloatField()),
                ('sampling_knee_intercept_up', models.FloatField()),
                ('sampling_hip_coef_up', models.FloatField()),
                ('sampling_hip_intercept_up', models.FloatField()),
                ('sampling_inside_hip_coef_up', models.FloatField()),
                ('sampling_inside_hip_intercept_up', models.FloatField()),
                ('sampling_waist_coef_down', models.FloatField()),
                ('sampling_waist_intercept_down', models.FloatField()),
                ('sampling_waist_coef_up', models.FloatField()),
                ('sampling_waist_intercept_up', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='SquatDatatest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('squat_state', models.JSONField(default=list)),
                ('accuracy', models.JSONField(default=list)),
                ('squat_count', models.IntegerField(default=0)),
                ('height', models.FloatField(default=0.0)),
                ('half_height', models.FloatField(default=0.0)),
                ('score', models.IntegerField(default=0)),
                ('reg', models.JSONField(default=list)),
            ],
        ),
    ]
